export const site = {
  name: "Uche Nnamani",
  url: "https://uchennamani.com",
  description:
    "Uche Nnamani is the founder and CEO of Fitness Space and co-founder of AERA. He writes about building products, startups, technology, community and entrepreneurship in Africa.",
  // Generated by src/app/opengraph-image.tsx. Pages that set their own
  // `openGraph` must include it, because metadata merges shallowly.
  ogImage: "/opengraph-image",
  email: "uche.nnamani@getfitness.space",
  links: {
    linkedin: "https://www.linkedin.com/in/uche-nnamani-928b0b19a/",
    x: "https://x.com/UcheNnamani4",
  },
  xHandle: "@UcheNnamani4",
};
